title: Dask based Flood Mapping
author: Martin Schobben & Thais Beham
logo: docs/images/tuw-geo-logo.svg
execute:
  execute_notebooks: cache

sphinx:
  extra_extensions:
  - 'sphinx.ext.duration'
  - 'sphinx.ext.doctest'
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'