name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install python package
        run: pip install ".[all]"
      - name: Build documentation
        run: jupyter-book build .
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: |
          (github.ref == 'refs/heads/main')
        with:
          #   token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: _build/html
