name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/itwinai
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Bump version
        run: make version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q build
      - name: Build package
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Commit new version
        run: |
          PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }}))
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit ${PATH} -m 'Bump version' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
