# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
#
# SPDX-License-Identifier: GPL-3.0-only
---
name: SQAaaS

on:
  push:
    branches: [main]

jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform
    steps:
      - name: Step definition for validating the workflow
        uses: eosc-synergy/sqaaas-step-action@v1
        with:
          name: pytest-step
          tool: pytest
          test_path: ./tests
          container: ghcr.io/intertwin-eu/dask-flood-mapper:latest
      - name: Print out payload
        run: cat pytest-step.json
      - name: SQAaaS assessment with unit testing (QC.Uni) step
        uses: eosc-synergy/sqaaas-assessment-action@v2
        with:
          qc_uni_steps: pytest-step
